"""
adjudicator.py
──────────────
The Adjudicator agent (CLAUDE.md §2, §2a, §6, §7). FIFTH and final stage of the
pipeline, after the Auditor (or straight from Researcher for informational queries).

It synthesizes findings across multiple sub-questions and provisions, resolves
conflicts between them (e.g., CPC procedural rules vs. substantive laws), respects
their relationships (causal / dependent / independent), and writes a structured final
adjudication with strict citations.

Public entry point:
    run_adjudicator(sub_questions: list[SubQuestion],
                    audit_results: dict[int, AuditResult],
                    evidence_pool: dict[int, list[Any]],
                    *,
                    llm: Any = None,
                    model: Optional[str] = None) -> AdjudicationResult
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv

from .llm_factory import build_rotating_structured_llm
from .schemas import AdjudicationResult, AuditResult, SubQuestion

# Adjudicator is the synthesis step (§4). Default to Groq llama-3.3-70b-versatile:
# reliable structured output via function_calling, rotated across GROQ_POOL.
_DEFAULT_MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """\
You are the Adjudicator for an Indian CIVIL-law (Code of Civil Procedure, Contract Act, etc.) legal assistant.
Your job is to synthesize all findings across multiple sub-questions, resolve conflicts between provisions (e.g. procedural CPC rules staying suits vs. substantive rights), respect dependent/causal relationships, and write the final legally-grounded answer.

You are given:
1. The sub-questions generated by the Query Agent.
2. The Audit Results (satisfied/failed/unknown conditions, determinations) from the Auditor for sub-questions that followed the full pipeline.
3. The Evidence Pool (retrieved text chunks and metadata) for each sub-question.

You MUST follow these strict rules to write the adjudication:
1. CITATION GUARANTEE: Every claim you make in the final response must cite a surviving verified condition (for test_application queries) or a retrieved evidence chunk (for informational queries).
   - For sub-questions that went through the full pipeline, you MUST ONLY rely on the conditions listed as "Surviving verified conditions (Auditor surviving_set)" in the Audit Result. If a critical condition was failed or unknown, explain that the provision does NOT apply because that condition was failed or unknown.
   - For sub-questions that are informational (short pipeline), use the evidence chunks provided in the "EVIDENCE POOL" directly, citing the document titles/breadcrumbs.
2. SYNTHESIZE RELATIONSHIPS:
   - If a sub-question is dependent on another, resolve the dependency in logical order.
   - If sub-questions are causal (e.g., landlord evicted because tenant refused illegal vacation request), synthesize them into a cohesive narrative rather than separate disjointed answers.
   - If independent, answer each separately but present them clearly under the same ultimate verdict.
3. CONFLICT RESOLUTION: Pay special attention to CPC procedural rules and how they conflict with substantive laws. For example, if a bankruptcy tribunal orders a moratorium under the Insolvency and Bankruptcy Code (IBC), it stays the continuation of civil suits against the corporate debtor. This means procedural law stays the suit, even if the plaintiff has valid substantive claims (e.g. for recovery of money). Make sure to resolve such conflicts explicitly.
4. MULTIPLE OPTIONS: If there are multiple legal options or paths depending on the surviving verified items or evidence (e.g., Option A: sue under Section X, Option B: seek relief under Rule Y), present them as distinct options. If only one path is viable, leave options empty.
"""


def build_adjudicator_llm(model: Optional[str] = None) -> Any:
    """
    Build a rotation-aware chat model that returns an `AdjudicationResult` directly.
    Explicit `model` arg > $ADJUDICATOR_MODEL > _DEFAULT_MODEL.
    """
    load_dotenv()
    model = model or os.environ.get("ADJUDICATOR_MODEL") or _DEFAULT_MODEL
    return build_rotating_structured_llm(AdjudicationResult, model)


def _render_sub_questions(
    sub_questions: List[SubQuestion],
    audit_results: Dict[int, AuditResult],
    evidence_pool: Dict[int, List[Any]],
) -> str:
    """Serialize sub-questions, audits, and evidence into a readable block for the LLM Human prompt."""
    lines = []
    for sq in sub_questions:
        lines.append(f"=== SUB-QUESTION {sq.id} ===")
        lines.append(f"Text: {sq.text}")
        lines.append(f"Query Type: {sq.query_type.value}")
        lines.append(f"Complexity: {sq.complexity.value}")
        lines.append(f"Relationship: {sq.relationship_type.value} (Depends on: {sq.depends_on})")
        lines.append(f"Provision Key: {sq.provision_key or 'None'}")
        
        # Facts and unknown fields from context
        lines.append(f"Extracted Facts: {sq.known_facts or sq.shared_context.known_facts}")
        if sq.shared_context.unknown_fields:
            lines.append(f"Gaps identified but not supplied (treated as unknown): {sq.shared_context.unknown_fields}")
            
        # Audit result (if full pipeline)
        audit = audit_results.get(sq.id)
        if audit:
            lines.append(f"--- AUDIT RESULT FOR SUB-QUESTION {sq.id} ---")
            lines.append(f"Provision: {audit.provision_key}")
            lines.append(f"Determination: {audit.determination}")
            
            surviving = audit.surviving_set if audit.surviving_set else audit.satisfied
            if surviving:
                lines.append("Surviving verified conditions (Auditor surviving_set):")
                for cond in surviving:
                    tag = "CRITICAL" if cond.critical else "optional"
                    alt = f" (alt: {cond.alternative_group})" if cond.alternative_group else ""
                    lines.append(f"  - [{tag}] {cond.text}{alt} -> {cond.rationale}")
            if audit.failed:
                lines.append("Failed conditions:")
                for cond in audit.failed:
                    tag = "CRITICAL" if cond.critical else "optional"
                    alt = f" (alt: {cond.alternative_group})" if cond.alternative_group else ""
                    lines.append(f"  - [{tag}] {cond.text}{alt} -> {cond.rationale}")
            if audit.unknown:
                lines.append("Unknown conditions:")
                for cond in audit.unknown:
                    tag = "CRITICAL" if cond.critical else "optional"
                    alt = f" (alt: {cond.alternative_group})" if cond.alternative_group else ""
                    lines.append(f"  - [{tag}] {cond.text}{alt} -> {cond.rationale}")
        else:
            lines.append("--- NO AUDIT RESULT (Short Pipeline / Informational) ---")
            
        # Evidence pool
        ev_list = evidence_pool.get(sq.id, [])
        if ev_list:
            lines.append(f"--- EVIDENCE POOL FOR SUB-QUESTION {sq.id} ---")
            for idx, chunk in enumerate(ev_list, start=1):
                if isinstance(chunk, dict):
                    title = chunk.get("title", "Unknown doc")
                    text = chunk.get("text", "")
                    # HybridRetriever emits "rrf_score"; accept either key.
                    score = chunk.get("score") or chunk.get("rrf_score") or 0.0
                else:
                    title = getattr(chunk, "title", getattr(chunk, "doc_id", "Unknown doc"))
                    text = getattr(chunk, "text", "")
                    score = getattr(chunk, "score", None) or getattr(chunk, "rrf_score", 0.0)
                
                # Truncate text to keep tokens reasonable while preserving depth
                preview = text[:1500] + ("..." if len(text) > 1500 else "")
                lines.append(f"Chunk {idx} (Title: {title}, Score: {score:.3f}):\n{preview}\n")
        else:
            lines.append("--- NO RETRIEVED EVIDENCE ---")
            
        lines.append("")
    return "\n".join(lines)


def run_adjudicator(
    sub_questions: List[SubQuestion],
    audit_results: Dict[int, AuditResult],
    evidence_pool: Dict[int, List[Any]],
    *,
    llm: Any = None,
    model: Optional[str] = None,
) -> AdjudicationResult:
    """
    Run the Adjudicator agent to synthesize final answers across all sub-questions.

    Args:
        sub_questions: list of SubQuestion objects from the Query Agent.
        audit_results: dictionary mapping sub-question ID to AuditResult.
        evidence_pool: dictionary mapping sub-question ID to list of retrieved chunks.
        llm:           injectable structured LLM for testing.
        model:         explicit model override when constructing rotating LLM.
    """
    # Defensive check: if no sub-questions, return an empty adjudication
    if not sub_questions:
        return AdjudicationResult(
            ultimate_verdict="No legal sub-questions were provided to adjudicate.",
            sub_answers=[],
            options=[],
            synthesis_and_conflicts="No sub-questions provided.",
        )

    # Render inputs for human message
    rendered_context = _render_sub_questions(sub_questions, audit_results, evidence_pool)
    human_content = (
        f"ADJUDICATION DATASET:\n\n{rendered_context}\n"
        "Generate a structured final legal adjudication following the guidelines."
    )

    messages = [("system", SYSTEM_PROMPT), ("human", human_content)]

    structured_llm = llm if llm is not None else build_adjudicator_llm(model)
    result: AdjudicationResult = structured_llm.invoke(messages)

    return result


if __name__ == "__main__":
    import json
    from .schemas import Complexity, QueryType, RelationshipType, SharedContext, AuditedCondition, AuditStatus

    # Manual test / execution verification
    print("Testing Adjudicator agent with mock data...")

    mock_shared = SharedContext(original_query="Evict company during bankruptcy moratorium?")
    mock_sq = SubQuestion(
        id=1,
        text="Can we proceed with the suit and evict the tenant company?",
        query_type=QueryType.TEST_APPLICATION,
        provision_key="Section 14 IBC",
        complexity=Complexity.MODERATE,
        relationship_type=RelationshipType.INDEPENDENT,
        known_facts=["Moratorium in place", "Company owes rent"],
        shared_context=mock_shared,
    )

    mock_audit = AuditResult(
        status="complete",
        provision_key="Section 14 Insolvency and Bankruptcy Code, 2016",
        determination="applies",
        satisfied=[
            AuditedCondition(
                group_label="Moratorium",
                text="moratorium declared prohibiting institution or continuation of suits",
                critical=True,
                status=AuditStatus.SATISFIED,
                rationale="The NCLT declared moratorium on 27.02.2018.",
            )
        ],
        surviving_set=[
            AuditedCondition(
                group_label="Moratorium",
                text="moratorium declared prohibiting institution or continuation of suits",
                critical=True,
                status=AuditStatus.SATISFIED,
                rationale="The NCLT declared moratorium on 27.02.2018.",
            )
        ],
        known_facts=["The NCLT declared moratorium on 27.02.2018."],
    )

    mock_evidence = [
        {
            "title": "M/S Golden Jubilee Hotels Limited vs Eih Ltd on 27 September, 2018",
            "score": 0.95,
            "text": "The moratorium order declared by the NCLT under Section 14 of the IBC stays all civil suit continuation.",
        }
    ]

    res = run_adjudicator([mock_sq], {1: mock_audit}, {1: mock_evidence})
    print("\n--- TEST ADJUDICATION RESULT ---")
    print(json.dumps(res.model_dump(), indent=2, default=str))
